version: '3'

services:
  cinematt-site-dev:
    container_name: cinematt_site_dev
    restart: on-failure
    build:
      context: .docker/site
      dockerfile: Dockerfile
      args:
        hugo_version: "0.20.2"
    ports:
      - "1313:1313"
    volumes:
      - ./:/opt:rw
    command: hugo server -s /opt/site --config /opt/site/config.yml --baseUrl http://cinematt.dev --bind "0.0.0.0" --appendPort=false --verbose

  cinematt-nginx-dev:
    container_name: cinematt_nginx_dev
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        nginx_conf: nginx.development.conf
    links:
      - cinematt-site-dev
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

  cinematt-js-dev:
    container_name: cinematt_js_dev
    restart: on-failure
    environment:
      - WATCH=true
      - SCRIPTS_DEST=./site/static/js
      - SVG_DEST=./site/static/svg
      - FAVICONS_DEST=./site/static/favicons
    image: node:7.10.0-alpine
    volumes:
      - ./:/opt:rw
    links:
      - cinematt-site-dev
    depends_on:
      - cinematt-site-dev
    command: sh -c "cd /opt && npm install && npm start"

  cinematt-sass-dev:
    container_name: cinematt_sass_dev
    image: ruby:2.1-alpine
    restart: on-failure
    volumes:
      - ./:/opt:rw
    links:
      - cinematt-site-dev
    depends_on:
      - cinematt-site-dev
    command: sh -c "gem install sass && sass --watch /opt/assets/sass/main.sass:/opt/site/static/css/main.css"

  